// To parse this JSON data, do
//
//     final vendor2 = vendor2FromJson(jsonString);

import 'package:meta/meta.dart';
import 'dart:convert';

Vendor2 vendor2FromJson(String str) => Vendor2.fromJson(json.decode(str));


class Vendor2 {
  Vendor2({
    required this.name,
    required this.logo,
    required this.total,
    required this.coordinate,
    required this.ok,
    required this.notOk,
    required this.timeSpan,
    required this.powerConsumed,
    required this.sysId,
    required this.autoGenerated,
    required this.frequency,
    required this.ccmsList
  });

  String name;
  String logo;
  int total;
  String coordinate;
  int ok;
  int notOk;
  String timeSpan;
  String powerConsumed;
  int sysId;
  bool autoGenerated;
  int frequency;
  List<String> ccmsList;

  factory Vendor2.fromJson(Map<String, dynamic> json) => Vendor2(
    name: json["name"] == null ? null : json["name"],
    logo: json["logo"] == null ? null : json["logo"],
    total: json["total"] == null ? null : json["total"],
    coordinate: json["coordinate"] == null ? null : json["coordinate"],
    ok: json["ok"] == null ? null : json["ok"],
    notOk: json["not_ok"] == null ? null : json["not_ok"],
    timeSpan: json["time_span"] == null ? null : json["time_span"],
    powerConsumed: json["power_consumed"] == null ? null : json["power_consumed"],
    sysId: json["sys_id"] == null ? null : json["sys_id"],
    autoGenerated: json["auto_generated"] == null ? null : json["auto_generated"],
    frequency: json["frequency"] == null ? null : json["frequency"],
    ccmsList: json["ccms_list"] == null ? [] : List<String>.from(json["ccms_list"].map((x) => x)),
  );


}
